# Esse docker-compose aglutina todos os microservices numa só estruturas
# Todos os serviços estão hospedados no docker-hub

services:
  
  #############################################################################################
  #       Ingress 
  #############################################################################################
  #       Server: Nginx
  #--------------------------------------------------------------------------------------------
  ingress:
    container_name: anselmex-ingress
    restart: on-failure
    build: 
      context: ./dockerfiles/ingress
      dockerfile: dockerfile
    ports:
      - 8080:80   
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Front End
  #############################################################################################  
  #       App: Angular
  #--------------------------------------------------------------------------------------------
  # anselmex-frontend-app:
  #   container_name: anselmex-frontend-app 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/frontend
  #     dockerfile: app.dockerfile
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Authentication Service
  #############################################################################################  
  #       App: C#
  #       Db : SQLServer
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------
   

  #############################################################################################
  #       Account Service
  #############################################################################################  
  #       App: Python
  #       Db : Postgres
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Bank Service
  ############################################################################################# 
  #       App: Python
  #       Db : MongoDB
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Market Service
  #############################################################################################  
  #       App: C#
  #       Db : SQLite
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Nft Service
  #############################################################################################  
  #       App: NodeJS
  #       Db : MariaDB
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------


  #############################################################################################
  #       Operator Service
  #############################################################################################  
  #       App: Go
  #       Db : MySQL
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------



  #############################################################################################
  #       Transfer Service
  ############################################################################################# 
  #       App: Java
  #       Db : MySQL
  #--------------------------------------------------------------------------------------------
  # anselmex-authentication-service:
  #   container_name: anselmex-authentication-service 
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: app.dockerfile         

  # anselmex-authentication-db:
  #   container_name: anselmex-authentication-db
  #   restart: on-failure
  #   build: 
  #     context: ./dockerfiles/authentication
  #     dockerfile: db.dockerfile     
  #--------------------------------------------------------------------------------------------


# volumes:
#   full-database:      
#   full-reverseproxy:
#   full-webapp:


# networks:
#   full-front:
#     driver: bridge
#   full-database:
#     driver: bridge    